#yaml config
openai: # OpenAI 相关配置
  # OpenAI API Key
  api_key: sk-abcde12345

  # API的网址
  base_url: https://api.openai.com/v1

  # 代理服务器地址。格式为"http://地址:端口号"
  proxy:

  # 聊天使用模型名称, 参见(https://platform.openai.com/docs/models/overview)
  chat_model: gpt-4-1106-preview

  # 作图参数, 参见(https://cookbook.openai.com/articles/what_is_new_with_dalle_3) 以及 api 说明
  image_model: dall-e-3   # (可选, 默认值: dall-e-3) 作图模型, 选项: dall-e-3, dall-e-2
  image_quality: hd  # (可选, 默认值: standard) 作图质量。选项: standard(标准), hd(高清)
  image_size: 1024x1024   # (可选, 默认值: 1024x1024) 作图大小, dall-e-3 支持尺寸1024x1024, 1792x1024, 1024x1792。

bot:  #机器人相关配置
  # 允许响应的群roomId (例如 2xxxxxx3@chatroom) 如果包含'$all'则响应所有群. 默认值=[$all]
  group_whitelist: [$all]  

  # 单聊消息只响应白名单中的微信号. 包含'$all'则响应所有单聊消息. 默认值=[$all]
  single_chat_whitelist: [$all]

  # 来自自己的消息, 只响应该前缀开头的, 否则忽略。默认值=[]
  self_prefix: ["$AI", "$ai"]

  # 单聊中只响应该前缀开头的消息, 不设置则响应所有消息. 默认值=[$ai]
  single_chat_prefix: []

admin:  # 管理员相关配置
  admins: [你的微信号]    # 管理员的微信号。只有管理员允许运行管理命令
  help: "$帮助"        # 显示帮助信息
  reload_config: "$刷新配置"  # 重新载入程序配置（本文件）
  clear_chat: "$清除"   # 清除记忆
  load_preset: "$加载"   # 为当前对话加载预设
  reset_preset: "$重置预设"  # 为当前对话重置预设到系统提示词